RING_PROPERTIES_DICT = {
    'brand_quality': ['high-end', 'regular'],
    'gold_color': ['yellow', 'white', 'rose', 'black'],
    'gold_carats': [18, 14, 9],
    'primary_stone': {
        'diamond': {
            'color': ['black', 'coffee', 'white', 'blue'],
            'cut': ['brilliant', 'princess', 'troidia', 'oval', 'baguette'],
            'quality': ['VVS1', 'VVS2', 'VS1', 'VS2', 'SI'],
            'clarity': ['D', 'E', 'F', 'G', 'LOWER'] 
        },
        'sapphire': {
            'color': ['rose', 'blue', 'yellow', 'white', 'pink', 'green', 'black'],
        },
        'garnet': {
            'color': ['green', 'orange', 'tsavorite'],
        },
        'amethyst': {},
        'onyx': {},
        'pearl': {
            'type' : ['akoya', 'south sea', 'edison fresh water', 'fresh water', 'edison']
        },
        'emerald': {
            'cut': ['baguette brilliant'],
            'properties': ['recrystallized']
        },
        'amazonite': {},
        'coral': {},
        'topaz': {
            'color': ['white', 'london blue', 'blue', 'rainforest', 'violac', 'blazing red', 'paraiba', 'aqua blue',
                      'baby pink', 'kashmir blue', 'green', 'red']
        },
        'tanzanite': {},
        'morganite': {},
        'ruby': {},
        'citrine': {},
        'qendrad': {},
        'zoisite': {},
        'quartz': {
            'color': ['pink']
        },
        'tourmaline': {},
        'spinel': {},
        'opal': {},
        'aquamarine': {},
        'rodolite': {}
    },
    'secondary_stones': {
        'diamonds': {
            'color': ['white', 'blue', 'coffee', 'black', 'blue'],
            'cut': ['brilliant', 'princess', 'troidia', 'pear shaped', 'triangle', 'baguette brilliant',
                    'marquise brilliant']
        },
        'emeralds': {},
        'garnets': {
            'color': ['tsavorite']
        },
        'peridots': {}, 
        'spinels': {},
        'carnelians': {},
        'chrysoprases': {},
        'lapis lazulis': {},
        'sapphires': {
            'color': ['blue pink', 'blue', 'green', 'pink'],
            'cut': ['baguette brilliant'],
        },
        'pearls': {},
        'mother of pearl': {
            'color': ['grey']
        }
    },
    'other': ['rhodium-finish', 'black-ceramic', 'black-lacquer']
}

INPUT_COLUMNS_LIST = ['total diamond carats',
                    'gold carats',
                    'jewel_weight',
                    'brilliant-diamonds',
                    'brilliant-diamond',
                    'black-ceramic',
                    'rose-sapphire',
                    'blue-sapphire',
                    'yellow-sapphire',
                    'green-garnet',
                    'orange-garnet',
                    'amethyst',
                    'emeralds',
                    'onyx',
                    'black-lacquer',
                    'tsavorite-garnets',
                    'tsavorite-garnet',
                    'peridots',
                    'diamonds',
                    'gray-mother-of-pearl',
                    'sapphire',
                    'emerald',
                    'spinels',
                    'carnelians',
                    'chrysoprases',
                    'lapis-lazulis',
                    'diamond',
                    'princess-diamond',
                    'brilliant-pavé-diamonds',
                    'troidia-diamond',
                    'baguette-diamonds',
                    'princess-diamonds',
                    'troidia-diamonds',
                    'rhodium-finish',
                    'pear-shaped-diamonds',
                    'amazonite',
                    'coral',
                    'recrystallized-emerald',
                    'topaz',
                    'white-topaz',
                    'tanzanite',
                    'london-blue-topaz',
                    'morganite',
                    'pearl',
                    'ruby',
                    'white-sapphire',
                    'blue-topaz',
                    'citrine',
                    'f',
                    'vs2',
                    'qendrad',
                    'e',
                    'g',
                    'vvs1',
                    'triangle-diamonds',
                    'spinel',
                    'blue-pink-sapphires',
                    'blue-sapphires',
                    'black-diamond',
                    'white-diamonds',
                    'pink-sapphire',
                    'opal',
                    'aquamarine',
                    'sapphires',
                    'baguette-brilliant-diamonds',
                    'green-sapphire',
                    'marquise-brilliant-diamonds',
                    'rodolite',
                    'coffee-diamonds',
                    'd',
                    'vvs2',
                    'akoya-pearl',
                    'oval-diamond',
                    'south-sea-pearl',
                    'baguette-brilliant-sapphires',
                    'baguette-brilliant-emerald',
                    'baguette-diamond',
                    'si',
                    'vs1',
                    'black-diamonds',
                    'black-sapphire',
                    'edison-fresh-water-pearl',
                    'fresh-water-pearl',
                    'edison-pearl',
                    'coffee-diamond',
                    'white-diamond',
                    'rainforest-topaz',
                    'violac-topaz',
                    'blazing-red-topaz',
                    'paraiba-topaz',
                    'aqua-blue-topaz',
                    'baby-pink-topaz',
                    'kashmir-blue-topaz',
                    'pearls',
                    'green-topaz',
                    'blue-diamonds',
                    'green-sapphires',
                    'pink-sapphires',
                    'perimeter-diamonds',
                    'zoisite',
                    'blue-diamond',
                    'red-topaz',
                    'pink-quartz',
                    'quartz',
                    'tourmaline',
                    'i',
                    'mother-of-pearl',
                    'brand_Haritidis',
                    'color_Black',
                    'color_Rose',
                    'color_White',
                    'color_Yellow']